In [3]:
import numpy as np

In [4]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [5]:
arr2 = np.array([1, 2, 3, 4], ndmin = 5)
print(arr2)
print(arr2.ndim) # prints the number of dimensions

[[[[[1 2 3 4]]]]]
5


In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr2[0:2, 1:4])

[5 6]
[2 4]
[1 3 5 7]
[[2 3 4]
 [7 8 9]]


In [7]:
arr2 = np.array([1, 2, 3, 4])
print(arr2.dtype)

int32


In [8]:
import numpy as np

arr = np.array([1, 0, 3])
newarr = arr.astype(bool) # converts array to type bool using: .astype()

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [9]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy() # .copy() takes array and is not affected by changes in arr
y = arr.view() # .view() takes array and is affected by changes in arr
arr[0] = 42
print(arr)
print(x)
print(y)

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]


In [10]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [13]:
arr = np.array([[[1, 2, 3], [4, 5, 6]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]


In [14]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr): # np.nditer() goes through all the scalar elements of an array
    print(x)

1
2
3
4
5
6
7
8


In [15]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr): # outputs with each dimension in a tuple
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [16]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [17]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis = 1) # axis=1 -> along the rows
print(arr)


[[1 2 5 6]
 [3 4 7 8]]


In [21]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)
arr = np.vstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2==0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [23]:
arr = np.array([1, 3, 5, 7]) # assuming a sorted array
x = np.searchsorted(arr, [2, 4, 6]) # finds the indices where the values 2, 4, 6 should be inserted
print(x) 

[1 2 3]


In [24]:
arr = np.array([3, 2, 0, 1])
x = np.sort(arr) # .sort() to sort an array 
print(x)

[0 1 2 3]


In [26]:
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42 
newarr = arr[filter_arr] # we can use a filtered array to output certain contents of arr 
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]
